import PageLayout from './PageLayout';
import usePreferredLang from './usePreferredLang';

export default function MedicalDisclaimer() {
  const lang = usePreferredLang();

  return (
    <PageLayout title={lang === 'en' ? 'Medical Disclaimer' : 'إخلاء المسؤولية الطبي'}>
      {lang === 'en' ? (
        <>
          <p>
            PhysioHub provides informational content and clinical calculators for
            educational purposes only. It is not medical advice and does not
            replace consultation with a qualified healthcare professional.
          </p>
          <h2>Not a diagnosis</h2>
          <p>
            The results generated by tools such as BMI, BMR, TDEE, and macro
            calculations are estimates based on established equations and
            assumptions. They should not be used for self-diagnosis or as a sole
            basis for treatment decisions.
          </p>
          <h2>When to seek professional help</h2>
          <p>
            If you have an injury, symptoms, chronic condition, pregnancy,
            eating disorder history, or any special medical circumstance, please
            consult a licensed physiotherapist, physician, or registered
            dietitian before making changes to your training or nutrition plan.
          </p>
        </>
      ) : (
        <>
          <p>
            منصة PhysioHub تقدم محتوى تثقيفي وحاسبات سريرية لأغراض تعليمية فقط.
            لا تُعد بديلاً عن الاستشارة الطبية ولا تُغني عن الرجوع لمختص رعاية
            صحية مؤهل.
          </p>
          <h2>ليست تشخيصاً</h2>
          <p>
            النتائج الناتجة عن أدوات مثل BMI وBMR وTDEE وحساب الماكروز هي تقديرات
            مبنية على معادلات وافتراضات معتمدة. لا ينبغي استخدامها للتشخيص الذاتي
            أو لاتخاذ قرارات علاجية بدون إشراف مختص.
          </p>
          <h2>متى يجب استشارة مختص</h2>
          <p>
            إذا كنت تعاني من إصابة أو أعراض أو حالة مزمنة أو حمل أو تاريخ اضطرابات
            أكل أو أي ظروف طبية خاصة، يرجى استشارة أخصائي علاج طبيعي أو طبيب أو
            أخصائي تغذية معتمد قبل إجراء أي تغييرات على خطة التدريب أو التغذية.
          </p>
        </>
      )}
    </PageLayout>
  );
}

