import PageLayout from './PageLayout';
import usePreferredLang from './usePreferredLang';
import Seo from '../components/seo/Seo';
import {buildHreflangs, navigationPaths} from '../utils/langUrlHelper';

export default function MedicalDisclaimer() {
  const lang = usePreferredLang();
  const isAr = lang === 'ar';
  const relatedLinks = [
    {
      label: isAr ? 'بروتوكولات الإصابات' : 'Injury protocols',
      href: navigationPaths.injuries(lang),
      description: isAr ? 'انتقل إلى أدلة التعافي والتأهيل العملية.' : 'Continue into the practical rehab and recovery guides.',
    },
    {
      label: isAr ? 'الدَّايت والأنظمة الغذائية' : 'Diet & regimens',
      href: navigationPaths.diets(lang),
      description: isAr ? 'استكشف أنظمة غذائية مختلفة مع ملاحظات أمان وأمثلة عملية.' : 'Explore diet types with educational cautions and examples.',
    },
    {
      label: isAr ? 'الشروط والأحكام' : 'Terms of service',
      href: navigationPaths.terms(lang),
      description: isAr ? 'راجع شروط استخدام المنصة التي تكمل هذا الإخلاء.' : 'Review the platform-wide terms that complement this disclaimer.',
    },
  ];

  return (
    <>
      <Seo
        title={isAr ? 'إخلاء المسؤولية الطبي' : 'Medical Disclaimer'}
        description={
          isAr
            ? 'إخلاء المسؤولية الطبي لمنصة PhysioNutrition وحاسبات العلاج الطبيعي والتغذية العلاجية.'
            : 'Medical disclaimer for PhysioNutrition physical therapy calculators and clinical nutrition tools.'
        }
        canonicalPath="/disclaimer"
        hreflangs={buildHreflangs('/disclaimer')}
      />
      <PageLayout title={isAr ? 'إخلاء المسؤولية الطبي' : 'Medical Disclaimer'} relatedLinks={relatedLinks}>
        {isAr ? (
          <>
            <p>منصة PhysioNutrition تقدم محتوى تثقيفي وحاسبات سريرية لأغراض تعليمية فقط. لا تُعد بديلًا عن الاستشارة الطبية ولا تُغني عن الرجوع لمختص رعاية صحية مؤهل.</p>

            <h2>ليست تشخيصًا</h2>
            <p>النتائج الناتجة عن أدوات مثل BMI وBMR وTDEE وحساب الماكروز هي تقديرات مبنية على معادلات وافتراضات معتمدة. لا ينبغي استخدامها للتشخيص الذاتي أو لاتخاذ قرارات علاجية بدون إشراف مختص.</p>

            <h2>متى يجب استشارة مختص</h2>
            <p>إذا كنت تعاني من إصابة أو أعراض أو حالة مزمنة أو حمل أو تاريخ اضطرابات أكل أو أي ظروف طبية خاصة، يرجى استشارة أخصائي علاج طبيعي أو طبيب أو أخصائي تغذية معتمد قبل إجراء أي تغييرات على خطة التدريب أو التغذية.</p>
          </>
        ) : (
          <>
            <p>PhysioNutrition provides informational content and clinical calculators for educational purposes only. It is not medical advice and does not replace consultation with a qualified healthcare professional.</p>

            <h2>Not a diagnosis</h2>
            <p>The results generated by tools such as BMI, BMR, TDEE, and macro calculations are estimates based on established equations and assumptions. They should not be used for self-diagnosis or as a sole basis for treatment decisions.</p>

            <h2>When to seek professional help</h2>
            <p>If you have an injury, symptoms, chronic condition, pregnancy, eating disorder history, or any special medical circumstance, please consult a licensed physiotherapist, physician, or registered dietitian before making changes to your training or nutrition plan.</p>
          </>
        )}
      </PageLayout>
    </>
  );
}
