create table if not exists public.protocols (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.phases (
  id bigint generated by default as identity primary key,
  protocol_id bigint not null references public.protocols(id) on delete cascade,
  phase_number integer not null,
  title text not null,
  timeline text,
  goals text[] not null default '{}',
  precautions text[] not null default '{}',
  criteria_to_progress text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  phase_id bigint not null references public.phases(id) on delete cascade,
  name text not null,
  parameters text,
  clinical_cue_rationale text,
  created_at timestamptz not null default now()
);

create index if not exists idx_protocols_name on public.protocols(name);
create index if not exists idx_phases_protocol_id on public.phases(protocol_id, phase_number);
create index if not exists idx_exercises_phase_id on public.exercises(phase_id);

alter table public.protocols enable row level security;
alter table public.phases enable row level security;
alter table public.exercises enable row level security;

grant select on table public.protocols to anon, authenticated;
grant select on table public.phases to anon, authenticated;
grant select on table public.exercises to anon, authenticated;

grant select, insert, update, delete on table public.protocols to authenticated;
grant select, insert, update, delete on table public.phases to authenticated;
grant select, insert, update, delete on table public.exercises to authenticated;

drop policy if exists "protocols_read" on public.protocols;
drop policy if exists "protocols_insert" on public.protocols;
drop policy if exists "protocols_update" on public.protocols;
drop policy if exists "protocols_delete" on public.protocols;

drop policy if exists "phases_read" on public.phases;
drop policy if exists "phases_insert" on public.phases;
drop policy if exists "phases_update" on public.phases;
drop policy if exists "phases_delete" on public.phases;

drop policy if exists "exercises_read" on public.exercises;
drop policy if exists "exercises_insert" on public.exercises;
drop policy if exists "exercises_update" on public.exercises;
drop policy if exists "exercises_delete" on public.exercises;

create policy "protocols_read" on public.protocols
for select
using (true);

create policy "protocols_insert" on public.protocols
for insert to authenticated
with check ((select count(1) from public.admin_users where user_id = auth.uid() and can_edit_injuries = true) > 0);

create policy "protocols_update" on public.protocols
for update to authenticated
using ((select count(1) from public.admin_users where user_id = auth.uid() and can_edit_injuries = true) > 0)
with check ((select count(1) from public.admin_users where user_id = auth.uid() and can_edit_injuries = true) > 0);

create policy "protocols_delete" on public.protocols
for delete to authenticated
using ((select count(1) from public.admin_users where user_id = auth.uid() and can_delete = true) > 0);

create policy "phases_read" on public.phases
for select
using (true);

create policy "phases_insert" on public.phases
for insert to authenticated
with check ((select count(1) from public.admin_users where user_id = auth.uid() and can_edit_phases = true) > 0);

create policy "phases_update" on public.phases
for update to authenticated
using ((select count(1) from public.admin_users where user_id = auth.uid() and can_edit_phases = true) > 0)
with check ((select count(1) from public.admin_users where user_id = auth.uid() and can_edit_phases = true) > 0);

create policy "phases_delete" on public.phases
for delete to authenticated
using ((select count(1) from public.admin_users where user_id = auth.uid() and can_delete = true) > 0);

create policy "exercises_read" on public.exercises
for select
using (true);

create policy "exercises_insert" on public.exercises
for insert to authenticated
with check ((select count(1) from public.admin_users where user_id = auth.uid() and can_edit_phases = true) > 0);

create policy "exercises_update" on public.exercises
for update to authenticated
using ((select count(1) from public.admin_users where user_id = auth.uid() and can_edit_phases = true) > 0)
with check ((select count(1) from public.admin_users where user_id = auth.uid() and can_edit_phases = true) > 0);

create policy "exercises_delete" on public.exercises
for delete to authenticated
using ((select count(1) from public.admin_users where user_id = auth.uid() and can_delete = true) > 0);
